restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "{{cookiecutter.submit_script}}"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs: 10
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.snakejob.sh"
use-conda: true
